export const StorePriceInfo: string;
export const StorePriceInfoNormal: string;
export const StorePriceInfoDiscount: string;
export const sizeM: string;
export const prices: string;
export const priceOriginal: string;
export const priceFinal: string;
export const discount: string;
export const sizeS: string;
