export const Carousel: string;
export const arrowLeft: string;
export const arrowRight: string;
export const items: string;
export const item: string;
export const itemFocused: string;
export const thumbs: string;
export const thumb: string;
export const thumbFocused: string;
